<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function checkout_form_place_autocom_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    
  if (($form_id == 'commerce_checkout_flow_multistep_default') || ($form_id == 'profile_customer_add_form')) {
    
    if (!empty($form_state->getStorage()['payment_information']['billing_information'])) {
      $form['#attached']['library'][] = 'checkout_form_place_autocom/google-maps-api';
      
      $form['custom_field'] = [
          '#type' => 'textfield',
          '#title' => t('Enter Address'),
          '#size' => 30,
          // '#required' => TRUE,
          '#weight' => -10,
          '#attributes' => [
              'id' => 'pac-input',
              'name' => 'ship-address',
          ]
      ];
    }
  }
}

